# Generated by Django 6.0.7 on 2026-07-30 02:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivo', '0006_remove_marca_unique_marca_nombre_and_more'),
        ('servicio', '0010_serviciocontratado_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente'), ('critica', 'Crítica')], db_index=True, default='normal', max_length=20, verbose_name='Prioridad')),
                ('fecha_programada', models.DateField(db_index=True, verbose_name='Fecha programada')),
                ('duracion_estimada', models.DurationField(blank=True, help_text='Tiempo estimado para completar la instalación.', null=True, verbose_name='Duración estimada')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('programada', 'Programada'), ('en_proceso', 'En proceso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('recibido_por', models.CharField(blank=True, max_length=150, verbose_name='Recibido por')),
                ('fecha_conformidad', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de conformidad')),
                ('observaciones_conformidad', models.TextField(blank=True, verbose_name='Observaciones de conformidad')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('servicio_contratado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones', to='servicio.serviciocontratado', verbose_name='Servicio contratado')),
            ],
            options={
                'verbose_name': 'Instalación',
                'verbose_name_plural': 'Instalaciones',
                'ordering': ('prioridad', 'fecha_programada', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='InstalacionDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad instalada de este dispositivo.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de serie')),
                ('direccion_mac', models.CharField(blank=True, max_length=17, verbose_name='Dirección MAC')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('usuario_acceso', models.CharField(blank=True, max_length=100, verbose_name='Usuario de acceso')),
                ('contrasena_acceso', models.CharField(blank=True, max_length=255, verbose_name='Contraseña de acceso')),
                ('ubicacion', models.CharField(blank=True, max_length=150, verbose_name='Ubicación')),
                ('estado', models.CharField(choices=[('instalado', 'Instalado'), ('retirado', 'Retirado'), ('reemplazado', 'Reemplazado'), ('fuera_servicio', 'Fuera de servicio')], db_index=True, default='instalado', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones', to='dispositivo.dispositivo', verbose_name='Dispositivo')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='instalacion.instalacion', verbose_name='Instalación')),
            ],
            options={
                'verbose_name': 'Dispositivo instalado',
                'verbose_name_plural': 'Dispositivos instalados',
                'ordering': ('ubicacion', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='InstalacionTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('rol', models.CharField(choices=[('responsable', 'Responsable'), ('ayudante', 'Ayudante'), ('supervisor', 'Supervisor')], default='ayudante', max_length=20, verbose_name='Rol')),
                ('es_responsable', models.BooleanField(db_index=True, default=False, help_text='Indica si este técnico es el responsable principal de la instalación.', verbose_name='Responsable')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='instalacion.instalacion', verbose_name='Instalación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Técnico de instalación',
                'verbose_name_plural': 'Técnicos de instalación',
                'ordering': ('-es_responsable', 'usuario'),
            },
        ),
        migrations.AddIndex(
            model_name='instalacion',
            index=models.Index(fields=['estado', 'fecha_programada'], name='instalacion_estado_7dd8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='instalaciondispositivo',
            index=models.Index(fields=['estado'], name='instalacion_estado_02f623_idx'),
        ),
        migrations.AddIndex(
            model_name='instalaciondispositivo',
            index=models.Index(fields=['ubicacion'], name='instalacion_ubicaci_5b6127_idx'),
        ),
        migrations.AddConstraint(
            model_name='instalaciondispositivo',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_serie', ''), _negated=True), fields=('instalacion', 'numero_serie'), name='unique_numero_serie_por_instalacion'),
        ),
        migrations.AddIndex(
            model_name='instalaciontecnico',
            index=models.Index(fields=['es_responsable'], name='instalacion_es_resp_6537d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='instalaciontecnico',
            constraint=models.UniqueConstraint(fields=('instalacion', 'usuario'), name='unique_tecnico_por_instalacion'),
        ),
    ]
