# Generated by Django 6.0.7 on 2026-07-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0009_remove_tipodispositivo_unique_tipo_dispositivo_nombre_and_more'),
        ('instalacion', '0002_remove_instalaciondispositivo_unique_numero_serie_por_instalacion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instalaciondispositivo',
            name='unique_num_ser_por_instal',
        ),
        migrations.AddConstraint(
            model_name='instalaciondispositivo',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_serie', ''), _negated=True), fields=('instalacion', 'numero_serie'), name='unique_num_serie_instal'),
        ),
    ]
