# Generated by Django 6.0.7 on 2026-07-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0009_remove_tipodispositivo_unique_tipo_dispositivo_nombre_and_more'),
        ('instalacion', '0003_remove_instalaciondispositivo_unique_num_ser_por_instal_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instalaciondispositivo',
            name='unique_num_serie_instal',
        ),
        migrations.RenameIndex(
            model_name='instalaciondispositivo',
            new_name='idx_inst_disp_estado',
            old_name='instalacion_estado_02f623_idx',
        ),
        migrations.RenameIndex(
            model_name='instalaciondispositivo',
            new_name='idx_inst_disp_ubic',
            old_name='instalacion_ubicaci_5b6127_idx',
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='contrasena_acceso',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Contraseña de acceso'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='direccion_mac',
            field=models.CharField(blank=True, default='', max_length=17, verbose_name='Dirección MAC'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='numero_serie',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Número de serie'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='observaciones',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='usuario_acceso',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Usuario de acceso'),
        ),
        migrations.AddIndex(
            model_name='instalaciondispositivo',
            index=models.Index(fields=['numero_serie'], name='idx_inst_disp_serie'),
        ),
    ]
