# Generated by Django 6.0.7 on 2026-07-30 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0009_remove_tipodispositivo_unique_tipo_dispositivo_nombre_and_more'),
        ('instalacion', '0004_remove_instalaciondispositivo_unique_num_serie_instal_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='instalaciondispositivo',
            new_name='idx_inst_disp_ubicacion',
            old_name='idx_inst_disp_ubic',
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad instalada del dispositivo.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='numero_serie',
            field=models.CharField(blank=True, default='', help_text='Identificador único del equipo físico.', max_length=100, verbose_name='Número de serie'),
        ),
        migrations.AddIndex(
            model_name='instalaciondispositivo',
            index=models.Index(fields=['instalacion', 'estado'], name='idx_inst_disp_inst_estado'),
        ),
        migrations.AddConstraint(
            model_name='instalaciondispositivo',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_serie', ''), _negated=True), fields=('numero_serie',), name='unique_instalacion_dispositivo_serie'),
        ),
    ]
