# Generated by Django 6.0.7 on 2026-08-01 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacion', '0005_rename_idx_inst_disp_ubic_idx_inst_disp_ubicacion_and_more'),
        ('servicio', '0010_serviciocontratado_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('programada', 'Programada'), ('en_proceso', 'En proceso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', help_text='Estado actual de la instalación.', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='fecha_conformidad',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se confirmó la conformidad de la instalación.', null=True, verbose_name='Fecha de conformidad'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se completó la instalación.', null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se inició la instalación.', null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='fecha_programada',
            field=models.DateField(db_index=True, help_text='Fecha en la que se programó la instalación.', verbose_name='Fecha programada'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones generales sobre la instalación.', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='observaciones_conformidad',
            field=models.TextField(blank=True, help_text='Observaciones generales sobre la conformidad de la instalación.', verbose_name='Observaciones de conformidad'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='prioridad',
            field=models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente'), ('critica', 'Crítica')], db_index=True, default='normal', help_text='Prioridad de la instalación.', max_length=20, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='recibido_por',
            field=models.CharField(blank=True, help_text='Nombre de la persona que recibió la instalación.', max_length=150, verbose_name='Recibido por'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='servicio_contratado',
            field=models.ForeignKey(blank=True, help_text='Servicio contratado al que pertenece la instalación.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones', to='servicio.serviciocontratado', verbose_name='Servicio contratado'),
        ),
    ]
