# Generated by Django 6.0.7 on 2026-08-05 01:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0009_remove_tipodispositivo_unique_tipo_dispositivo_nombre_and_more'),
        ('instalacion', '0006_alter_instalacion_estado_and_more'),
        ('servicio', '0010_serviciocontratado_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instalaciondispositivo',
            name='unique_instalacion_dispositivo_serie',
        ),
        migrations.RemoveConstraint(
            model_name='instalaciontecnico',
            name='unique_tecnico_por_instalacion',
        ),
        migrations.RemoveIndex(
            model_name='instalaciondispositivo',
            name='idx_inst_disp_estado',
        ),
        migrations.RemoveIndex(
            model_name='instalaciondispositivo',
            name='idx_inst_disp_ubicacion',
        ),
        migrations.RemoveIndex(
            model_name='instalaciondispositivo',
            name='idx_inst_disp_serie',
        ),
        migrations.RemoveIndex(
            model_name='instalaciontecnico',
            name='instalacion_es_resp_6537d6_idx',
        ),
        migrations.RenameIndex(
            model_name='instalacion',
            new_name='idx_inst_estado_fecha',
            old_name='instalacion_estado_7dd8bd_idx',
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='fecha_conformidad',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se registró la conformidad.', null=True, verbose_name='Fecha de conformidad'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora reales de finalización de la instalación.', null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora reales de inicio de la instalación.', null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='fecha_programada',
            field=models.DateField(db_index=True, help_text='Fecha prevista para ejecutar la instalación.', verbose_name='Fecha programada'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='observaciones',
            field=models.TextField(blank=True, default='', help_text='Observaciones generales sobre la instalación.', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='observaciones_conformidad',
            field=models.TextField(blank=True, default='', help_text='Observaciones relacionadas con la recepción y conformidad de la instalación.', verbose_name='Observaciones de conformidad'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='prioridad',
            field=models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente'), ('critica', 'Crítica')], db_index=True, default='normal', help_text='Prioridad operativa de la instalación.', max_length=20, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='recibido_por',
            field=models.CharField(blank=True, default='', help_text='Nombre de la persona que recibió la instalación.', max_length=150, verbose_name='Recibido por'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='servicio_contratado',
            field=models.ForeignKey(blank=True, help_text='Servicio contratado asociado con la instalación, si corresponde.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones', to='servicio.serviciocontratado', verbose_name='Servicio contratado'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='contrasena_acceso',
            field=models.CharField(blank=True, default='', help_text='Contraseña utilizada para acceder al dispositivo.', max_length=255, verbose_name='Contraseña de acceso'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IPv4 o IPv6 asignada al dispositivo.', null=True, unpack_ipv4=True, verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='direccion_mac',
            field=models.CharField(blank=True, help_text='Dirección MAC única del equipo. Ejemplo: AA:BB:CC:DD:EE:FF.', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese una dirección MAC válida. Ejemplo: AA:BB:CC:DD:EE:FF.', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')], verbose_name='Dirección MAC'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='dispositivo',
            field=models.ForeignKey(help_text='Producto del catálogo correspondiente al equipo físico.', on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos_instalados', to='dispositivo.dispositivo', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='estado',
            field=models.CharField(choices=[('instalado', 'Instalado'), ('retirado', 'Retirado'), ('reemplazado', 'Reemplazado'), ('fuera_servicio', 'Fuera de servicio')], db_index=True, default='instalado', help_text='Estado actual del equipo físico instalado.', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='instalacion',
            field=models.ForeignKey(help_text='Instalación a la que pertenece el equipo físico.', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='instalacion.instalacion', verbose_name='Instalación'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='numero_serie',
            field=models.CharField(blank=True, help_text='Número de serie único del equipo físico.', max_length=100, null=True, unique=True, verbose_name='Número de serie'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='observaciones',
            field=models.TextField(blank=True, default='', help_text='Observaciones técnicas sobre el dispositivo instalado.', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='ubicacion',
            field=models.CharField(blank=True, default='', help_text='Ubicación física del dispositivo dentro de la instalación.', max_length=150, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='instalaciondispositivo',
            name='usuario_acceso',
            field=models.CharField(blank=True, default='', help_text='Nombre de usuario utilizado para acceder al dispositivo.', max_length=100, verbose_name='Usuario de acceso'),
        ),
        migrations.AlterField(
            model_name='instalaciontecnico',
            name='es_responsable',
            field=models.BooleanField(default=False, help_text='Indica si este técnico es el responsable principal de la instalación.', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='instalaciontecnico',
            name='observaciones',
            field=models.TextField(blank=True, default='', help_text='Observaciones relacionadas con la participación del técnico.', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='instalaciontecnico',
            name='rol',
            field=models.CharField(choices=[('responsable', 'Responsable'), ('ayudante', 'Ayudante'), ('supervisor', 'Supervisor')], default='ayudante', help_text='Rol desempeñado por el técnico durante la instalación.', max_length=20, verbose_name='Rol'),
        ),
        migrations.AddIndex(
            model_name='instalaciondispositivo',
            index=models.Index(fields=['instalacion', 'ubicacion'], name='idx_inst_disp_inst_ubic'),
        ),
        migrations.AddConstraint(
            model_name='instalaciontecnico',
            constraint=models.UniqueConstraint(fields=('instalacion', 'usuario'), name='unique_instalacion_tecnico'),
        ),
        migrations.RemoveField(
            model_name='instalaciondispositivo',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='instalaciontecnico',
            name='codigo',
        ),
    ]
