# Generated by Django 6.0.7 on 2026-08-05 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacion', '0007_remove_instalaciondispositivo_unique_instalacion_dispositivo_serie_and_more'),
        ('orden_trabajo', '0011_remove_ordentrabajo_instalacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalacion',
            name='servicio_contratado',
        ),
        migrations.AddField(
            model_name='instalacion',
            name='orden_trabajo',
            field=models.OneToOneField(default=1, help_text='Orden de trabajo que dio origen a esta instalación.', on_delete=django.db.models.deletion.PROTECT, related_name='instalacion', to='orden_trabajo.ordentrabajo', verbose_name='Orden de trabajo'),
            preserve_default=False,
        ),
    ]
