# Generated by Django 6.0.7 on 2026-08-17 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacion', '0008_remove_instalacion_servicio_contratado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='usuario_conformidad',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que registró formalmente la conformidad de la instalación.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conformidades_instalacion_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
