# Generated by Django 6.0.7 on 2026-07-30 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instalacion', '0005_rename_idx_inst_disp_ubic_idx_inst_disp_ubicacion_and_more'),
        ('proyecto', '0003_alter_proyecto_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.CharField(blank=True, default='', max_length=500, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('INSTALACION', 'Instalación'), ('MANTENIMIENTO', 'Mantenimiento'), ('REPARACION', 'Reparación'), ('REINSTALACION', 'Reinstalación'), ('DESINSTALACION', 'Desinstalación'), ('VISITA_TECNICA', 'Visita técnica'), ('INSPECCION', 'Inspección'), ('GARANTIA', 'Garantía')], db_index=True, default='INSTALACION', max_length=30, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('PROGRAMADA', 'Programada'), ('EN_PROCESO', 'En proceso'), ('PAUSADA', 'Pausada'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='BORRADOR', max_length=30, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], db_index=True, default='MEDIA', max_length=20, verbose_name='Prioridad')),
                ('fecha_programada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha programada')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha finalización')),
                ('observaciones', models.TextField(blank=True, default='', max_length=1000, verbose_name='Observaciones')),
                ('instalacion', models.ForeignKey(blank=True, help_text='Instalación relacionada si corresponde.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='instalacion.instalacion', verbose_name='Instalación')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='proyecto.proyecto', verbose_name='Proyecto')),
                ('responsable', models.ForeignKey(help_text='Usuario responsable de coordinar la orden.', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('archivo', models.FileField(upload_to='ordenes_trabajo/%Y/%m/', verbose_name='Archivo')),
                ('descripcion', models.CharField(blank=True, default='', max_length=150, verbose_name='Descripción')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='orden_trabajo.ordentrabajo', verbose_name='Orden de trabajo')),
                ('usuario', models.ForeignKey(help_text='Usuario que cargó el archivo.', on_delete=django.db.models.deletion.PROTECT, related_name='archivos_ordenes_trabajo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Archivo de orden de trabajo',
                'verbose_name_plural': 'Archivos de órdenes de trabajo',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajoSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='orden_trabajo.ordentrabajo', verbose_name='Orden de trabajo')),
                ('usuario', models.ForeignKey(help_text='Usuario que registra el seguimiento.', on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_ordenes_trabajo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Seguimiento de orden de trabajo',
                'verbose_name_plural': 'Seguimientos de órdenes de trabajo',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('es_principal', models.BooleanField(default=False, help_text='Indica si es el técnico principal de la orden.', verbose_name='Técnico principal')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='orden_trabajo.ordentrabajo', verbose_name='Orden de trabajo')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Técnico asignado',
                'verbose_name_plural': 'Técnicos asignados',
                'ordering': ('-es_principal', 'tecnico'),
            },
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['estado', 'prioridad'], name='idx_ot_estado_prioridad'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['fecha_programada'], name='idx_ot_fecha_prog'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['proyecto'], name='idx_ot_proyecto'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajoarchivo',
            index=models.Index(fields=['orden_trabajo'], name='idx_ot_archivo_ot'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajoarchivo',
            index=models.Index(fields=['usuario'], name='idx_ot_archivo_usuario'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajoseguimiento',
            index=models.Index(fields=['orden_trabajo', 'created_at'], name='idx_ot_seg_fecha'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajoseguimiento',
            index=models.Index(fields=['usuario'], name='idx_ot_seg_usuario'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajotecnico',
            index=models.Index(fields=['orden_trabajo'], name='idx_ot_tecnico_ot'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajotecnico',
            index=models.Index(fields=['tecnico'], name='idx_ot_tecnico_usuario'),
        ),
        migrations.AddConstraint(
            model_name='ordentrabajotecnico',
            constraint=models.UniqueConstraint(fields=('orden_trabajo', 'tecnico'), name='unique_ot_tecnico'),
        ),
    ]
