# Generated by Django 6.0.7 on 2026-08-01 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0003_alter_sucursal_cuenta_cliente'),
        ('instalacion', '0006_alter_instalacion_estado_and_more'),
        ('orden_trabajo', '0001_initial'),
        ('proyecto', '0003_alter_proyecto_descripcion'),
        ('servicio', '0010_serviciocontratado_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ordentrabajo',
            name='idx_ot_estado_prioridad',
        ),
        migrations.RemoveIndex(
            model_name='ordentrabajo',
            name='idx_ot_proyecto',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el cliente aceptó.', null=True, verbose_name='Fecha aceptación'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_cobro',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se cobró la orden.', null=True, verbose_name='Fecha cobro'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_envio_cliente',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se envió la orden al cliente.', null=True, verbose_name='Fecha envío al cliente'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_facturacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se facturó la orden.', null=True, verbose_name='Fecha facturación'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='servicio_contratado',
            field=models.ForeignKey(blank=True, help_text='Servicio contratado relacionado si corresponde.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='servicio.serviciocontratado', verbose_name='Servicio Contratado'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucrusal relacionada si corresponde.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='cuenta_cliente.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='usuario_aceptacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que confirmo la aceptacion del cliente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_aceptadas', to=settings.AUTH_USER_MODEL, verbose_name='Aceptado por'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='usuario_cobro',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó el cobro de la orden.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_cobradas', to=settings.AUTH_USER_MODEL, verbose_name='Cobrado por'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='usuario_envio_cliente',
            field=models.ForeignKey(blank=True, help_text='Usuario que envió la orden al cliente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='usuario_facturacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que facturó la orden.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_facturadas', to=settings.AUTH_USER_MODEL, verbose_name='Facturado por'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='usuario_finalizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que finalizó la ejecución de la orden.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_finalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Finalizado por'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='usuario_inicio',
            field=models.ForeignKey(blank=True, help_text='Usuario que inició la ejecución de la orden.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_iniciadas', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción detallada de la orden de trabajo.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de finalización de la ejecución de la orden.', null=True, verbose_name='Fecha finalización'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de inicio de la ejecución de la orden.', null=True, verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_programada',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora programada para la ejecución de la orden.', null=True, verbose_name='Fecha programada'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='instalacion',
            field=models.OneToOneField(blank=True, help_text='Instalación relacionada si corresponde.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='instalacion.instalacion', verbose_name='Instalación'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='observaciones',
            field=models.TextField(blank=True, default='', help_text='Observaciones generales sobre la orden de trabajo.', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto relacionado si corresponde.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='proyecto.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='responsable',
            field=models.ForeignKey(help_text='Usuario responsable de coordinar la orden.', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='titulo',
            field=models.CharField(help_text='Título de la orden de trabajo.', max_length=150, verbose_name='Título'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['estado'], name='idx_ot_estado'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['prioridad'], name='idx_ot_prioridad'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['responsable'], name='idx_ot_responsable'),
        ),
    ]
