# Generated by Django 6.0.7 on 2026-08-01 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacion', '0006_alter_instalacion_estado_and_more'),
        ('orden_trabajo', '0002_remove_ordentrabajo_idx_ot_estado_prioridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='instalacion',
            field=models.OneToOneField(blank=True, help_text='Instalación relacionada si corresponde.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orden_trabajo', to='instalacion.instalacion', verbose_name='Instalación'),
        ),
    ]
