# Generated by Django 6.0.7 on 2026-08-01 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0003_alter_ordentrabajo_instalacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_recepcion_solicitud',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que la empresa recibió la solicitud del cliente.', null=True, verbose_name='Fecha recepción de la solicitud'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='usuario_recepcion_solicitud',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró la recepción de la solicitud.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Recepcionado por'),
        ),
    ]
