# Generated by Django 6.0.7 on 2026-08-01 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacion', '0006_alter_instalacion_estado_and_more'),
        ('orden_trabajo', '0004_ordentrabajo_fecha_recepcion_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='instalacion_origen',
            field=models.ForeignKey(blank=True, help_text='Instalación relacionada si corresponde.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='instalacion.instalacion', verbose_name='Instalación relacionada'),
        ),
    ]
