# Generated by Django 6.0.7 on 2026-08-01 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacion', '0006_alter_instalacion_estado_and_more'),
        ('orden_trabajo', '0005_ordentrabajo_instalacion_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='instalacion_origen',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='instalacion_relacionada',
            field=models.ForeignKey(blank=True, help_text='Instalación existente sobre la cual se realizará el trabajo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_relacionadas', to='instalacion.instalacion', verbose_name='Instalación relacionada'),
        ),
    ]
