# Generated by Django 6.0.7 on 2026-08-01 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0006_remove_ordentrabajo_instalacion_origen_and_more'),
        ('telecom', '0004_remove_presupuestotelecom_w0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='presupuesto_telecom',
            field=models.ForeignKey(blank=True, help_text='Presupuesto de telecom relacionado si corresponde.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='telecom.presupuestotelecom', verbose_name='Presupuesto Telecom'),
        ),
    ]
