# Generated by Django 6.0.7 on 2026-08-02 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0003_alter_sucursal_cuenta_cliente'),
        ('instalacion', '0006_alter_instalacion_estado_and_more'),
        ('orden_trabajo', '0008_remove_ordentrabajo_fecha_programada'),
        ('proyecto', '0003_alter_proyecto_descripcion'),
        ('servicio', '0010_serviciocontratado_proyecto'),
        ('telecom', '0004_remove_presupuestotelecom_w0_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_programada',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora programada para la ejecución de la orden.', null=True, verbose_name='Fecha programada'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['fecha_programada'], name='idx_ot_fecha_prog'),
        ),
    ]
