# Generated by Django 6.0.7 on 2026-08-04 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0003_alter_sucursal_cuenta_cliente'),
        ('instalacion', '0006_alter_instalacion_estado_and_more'),
        ('orden_trabajo', '0009_ordentrabajo_fecha_programada_and_more'),
        ('proyecto', '0005_proyectodetalle_and_more'),
        ('servicio', '0010_serviciocontratado_proyecto'),
        ('telecom', '0006_alter_conceptotelecom_moneda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ordentrabajoarchivo',
            name='idx_ot_archivo_ot',
        ),
        migrations.RemoveIndex(
            model_name='ordentrabajoarchivo',
            name='idx_ot_archivo_usuario',
        ),
        migrations.RemoveIndex(
            model_name='ordentrabajoseguimiento',
            name='idx_ot_seg_usuario',
        ),
        migrations.RemoveIndex(
            model_name='ordentrabajotecnico',
            name='idx_ot_tecnico_ot',
        ),
        migrations.RemoveIndex(
            model_name='ordentrabajotecnico',
            name='idx_ot_tecnico_usuario',
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción detallada del trabajo que debe realizarse.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el cliente aceptó la orden.', null=True, verbose_name='Fecha de aceptación'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_cobro',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se registró el cobro de la orden.', null=True, verbose_name='Fecha de cobro'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_envio_cliente',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que la orden fue enviada al cliente.', null=True, verbose_name='Fecha de envío al cliente'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_facturacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se facturó la orden.', null=True, verbose_name='Fecha de facturación'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que finalizó la ejecución de la orden.', null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que comenzó la ejecución de la orden.', null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_programada',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora programadas para ejecutar la orden.', null=True, verbose_name='Fecha programada'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_recepcion_solicitud',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que la empresa recibió la solicitud del cliente.', null=True, verbose_name='Fecha de recepción de la solicitud'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='instalacion',
            field=models.OneToOneField(blank=True, help_text='Instalación generada o asociada directamente con esta orden de trabajo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orden_trabajo', to='instalacion.instalacion', verbose_name='Instalación'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='presupuesto_telecom',
            field=models.ForeignKey(blank=True, help_text='Presupuesto Telecom relacionado con la orden de trabajo, si corresponde.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='telecom.presupuestotelecom', verbose_name='Presupuesto Telecom'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto relacionado con la orden de trabajo, si corresponde.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='proyecto.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='responsable',
            field=models.ForeignKey(help_text='Usuario responsable de coordinar la orden de trabajo.', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='servicio_contratado',
            field=models.ForeignKey(blank=True, help_text='Servicio contratado relacionado con la orden de trabajo, si corresponde.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='servicio.serviciocontratado', verbose_name='Servicio contratado'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal relacionada con la orden de trabajo, si corresponde.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='cuenta_cliente.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='titulo',
            field=models.CharField(help_text='Título descriptivo de la orden de trabajo.', max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='usuario_aceptacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró la aceptación del cliente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_aceptadas', to=settings.AUTH_USER_MODEL, verbose_name='Aceptación registrada por'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='usuario_cobro',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró el cobro de la orden.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_cobradas', to=settings.AUTH_USER_MODEL, verbose_name='Cobrado por'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='usuario_envio_cliente',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró el envío de la orden al cliente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='usuario_facturacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró la facturación de la orden.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_facturadas', to=settings.AUTH_USER_MODEL, verbose_name='Facturado por'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='usuario_finalizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró la finalización de la orden.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_finalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Finalizado por'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='usuario_inicio',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró el inicio de la orden.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_iniciadas', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por'),
        ),
        migrations.AlterField(
            model_name='ordentrabajoarchivo',
            name='archivo',
            field=models.FileField(help_text='Documento, fotografía o archivo técnico relacionado con la orden de trabajo.', upload_to='ordenes_trabajo/%Y/%m/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='ordentrabajoarchivo',
            name='descripcion',
            field=models.CharField(blank=True, default='', help_text='Descripción breve del contenido del archivo.', max_length=150, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ordentrabajoseguimiento',
            name='comentario',
            field=models.TextField(help_text='Descripción de la novedad, avance o actualización de la orden de trabajo.', verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='ordentrabajoseguimiento',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que registró el seguimiento.', on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_ordenes_trabajo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='ordentrabajotecnico',
            name='es_principal',
            field=models.BooleanField(default=False, help_text='Indica si el técnico es el responsable principal de ejecutar la orden.', verbose_name='Técnico principal'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['proyecto', 'estado'], name='idx_ot_proy_estado'),
        ),
    ]
