# Generated by Django 6.0.7 on 2026-08-05 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0010_remove_ordentrabajoarchivo_idx_ot_archivo_ot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='instalacion',
        ),
    ]
