# Generated by Django 6.0.7 on 2026-08-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0011_remove_ordentrabajo_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajotecnico',
            name='observaciones',
            field=models.TextField(blank=True, default='', help_text='Observaciones relacionadas con la participación del técnico en la orden de trabajo.', verbose_name='Observaciones'),
        ),
    ]
