# Generated by Django 6.0.7 on 2026-08-05 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0003_alter_sucursal_cuenta_cliente'),
        ('instalacion', '0008_remove_instalacion_servicio_contratado_and_more'),
        ('orden_trabajo', '0012_alter_ordentrabajotecnico_observaciones'),
        ('proyecto', '0006_remove_proyectodetalle_uq_proydet_proy_orden_and_more'),
        ('servicio', '0010_serviciocontratado_proyecto'),
        ('telecom', '0006_alter_conceptotelecom_moneda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ordentrabajo',
            name='idx_ot_estado',
        ),
        migrations.RemoveIndex(
            model_name='ordentrabajo',
            name='idx_ot_prioridad',
        ),
        migrations.RemoveIndex(
            model_name='ordentrabajo',
            name='idx_ot_responsable',
        ),
        migrations.RemoveIndex(
            model_name='ordentrabajo',
            name='idx_ot_fecha_prog',
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['servicio_contratado', 'estado'], name='idx_ot_serv_estado'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['responsable', 'fecha_programada'], name='idx_ot_resp_fecha'),
        ),
    ]
