# Generated by Django 6.0.7 on 2026-08-10 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0013_remove_ordentrabajo_idx_ot_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='estado_aceptacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], db_index=True, default='PENDIENTE', help_text='Indica si el cliente todavía no respondió, aceptó o rechazó la propuesta.', max_length=20, verbose_name='Respuesta del cliente'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el cliente respondió la propuesta.', null=True, verbose_name='Fecha de respuesta del cliente'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_envio_cliente',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se envió al cliente la propuesta asociada a la orden.', null=True, verbose_name='Fecha de envío al cliente'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='usuario_aceptacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró la respuesta del cliente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_aceptadas', to=settings.AUTH_USER_MODEL, verbose_name='Respuesta registrada por'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='usuario_envio_cliente',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró el envío al cliente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
    ]
