# Generated by Django 6.0.7 on 2026-08-18 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0014_ordentrabajo_estado_aceptacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajotecnico',
            options={'ordering': ('-is_active', '-es_principal', 'tecnico'), 'verbose_name': 'Técnico asignado', 'verbose_name_plural': 'Técnicos asignados'},
        ),
        migrations.AddField(
            model_name='ordentrabajotecnico',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el técnico fue asignado a la orden.', null=True, verbose_name='Fecha de asignación'),
        ),
        migrations.AddField(
            model_name='ordentrabajotecnico',
            name='fecha_desasignacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el técnico fue desasignado de la orden.', null=True, verbose_name='Fecha de desasignación'),
        ),
        migrations.AddField(
            model_name='ordentrabajotecnico',
            name='usuario_asignacion',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que registró formalmente la asignación del técnico.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_tecnicos_ot_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por'),
        ),
        migrations.AddField(
            model_name='ordentrabajotecnico',
            name='usuario_desasignacion',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que registró formalmente la desasignación del técnico.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='desasignaciones_tecnicos_ot_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Desasignado por'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajotecnico',
            index=models.Index(fields=['orden_trabajo', 'is_active'], name='idx_ot_tec_activo'),
        ),
    ]
