# Generated by Django 6.0.7 on 2026-08-19 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0015_alter_ordentrabajotecnico_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajoseguimiento',
            options={'ordering': ('-fecha_seguimiento', '-created_at'), 'verbose_name': 'Seguimiento de orden de trabajo', 'verbose_name_plural': 'Seguimientos de órdenes de trabajo'},
        ),
        migrations.RemoveIndex(
            model_name='ordentrabajoseguimiento',
            name='idx_ot_seg_fecha',
        ),
        migrations.AddField(
            model_name='ordentrabajoseguimiento',
            name='fecha_seguimiento',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora real en que ocurrió la novedad o actualización.', null=True, verbose_name='Fecha del seguimiento'),
        ),
        migrations.AlterField(
            model_name='ordentrabajoseguimiento',
            name='usuario',
            field=models.ForeignKey(editable=False, help_text='Usuario que registró formalmente el seguimiento.', on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_ordenes_trabajo', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajoseguimiento',
            index=models.Index(fields=['orden_trabajo', 'fecha_seguimiento'], name='idx_ot_seg_fecha'),
        ),
    ]
