# Generated by Django 6.0.7 on 2026-08-19 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0016_alter_ordentrabajoseguimiento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajoarchivo',
            options={'ordering': ('-is_active', '-fecha_documento', '-created_at'), 'verbose_name': 'Archivo de orden de trabajo', 'verbose_name_plural': 'Archivos de órdenes de trabajo'},
        ),
        migrations.AddField(
            model_name='ordentrabajoarchivo',
            name='fecha_documento',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora asociada al documento, fotografía o evidencia.', null=True, verbose_name='Fecha del documento'),
        ),
        migrations.AddField(
            model_name='ordentrabajoarchivo',
            name='fecha_retiro',
            field=models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora en que el archivo fue retirado del flujo operativo.', null=True, verbose_name='Fecha de retiro'),
        ),
        migrations.AddField(
            model_name='ordentrabajoarchivo',
            name='motivo_retiro',
            field=models.CharField(blank=True, default='', editable=False, help_text='Motivo por el cual el archivo dejó de considerarse activo.', max_length=250, verbose_name='Motivo del retiro'),
        ),
        migrations.AddField(
            model_name='ordentrabajoarchivo',
            name='usuario_retiro',
            field=models.ForeignKey(blank=True, editable=False, help_text='Usuario que retiró formalmente el archivo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archivos_ot_retirados', to=settings.AUTH_USER_MODEL, verbose_name='Retirado por'),
        ),
        migrations.AlterField(
            model_name='ordentrabajoarchivo',
            name='usuario',
            field=models.ForeignKey(editable=False, help_text='Usuario que registró formalmente el archivo en la orden de trabajo.', on_delete=django.db.models.deletion.PROTECT, related_name='archivos_ordenes_trabajo', to=settings.AUTH_USER_MODEL, verbose_name='Cargado por'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajoarchivo',
            index=models.Index(fields=['orden_trabajo', 'is_active'], name='idx_ot_arch_activo'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajoarchivo',
            index=models.Index(fields=['orden_trabajo', 'fecha_documento'], name='idx_ot_arch_fecha'),
        ),
    ]
