# Generated by Django 6.0.7 on 2026-07-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de dispositivo',
                'verbose_name_plural': 'Tipos de dispositivos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ('nombre',),
                'constraints': [models.UniqueConstraint(fields=('nombre',), name='unique_marca_nombre')],
            },
        ),
    ]
