# Generated by Django 6.0.7 on 2026-07-24 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del modelo')),
                ('descripcion', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
                ('fabricante_codigo', models.CharField(blank=True, help_text='Código o número de parte utilizado por el fabricante.', max_length=20, verbose_name='Código del fabricante')),
                ('ean', models.CharField(blank=True, help_text='Código comercial EAN/GTIN del producto.', max_length=20, verbose_name='Código EAN')),
                ('fabricado', models.BooleanField(default=True, help_text='Indica si el fabricante continúa produciendo este modelo.', verbose_name='Fabricado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='dispositivo.marca', verbose_name='Marca')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='dispositivo.tipodispositivo', verbose_name='Tipo de dispositivo')),
            ],
            options={
                'verbose_name': 'Modelo de dispositivo',
                'verbose_name_plural': 'Modelos de dispositivos',
                'ordering': ('marca__nombre', 'nombre'),
                'constraints': [models.UniqueConstraint(fields=('marca', 'nombre'), name='unique_modelo_por_marca')],
            },
        ),
    ]
