# Generated by Django 6.0.7 on 2026-07-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0002_modelodispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelodispositivo',
            name='url_datas_heet',
            field=models.URLField(blank=True, verbose_name='Hoja de datos'),
        ),
    ]
