# Generated by Django 6.0.7 on 2026-07-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0003_modelodispositivo_url_datas_heet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelodispositivo',
            name='url_datas_heet',
            field=models.URLField(blank=True, help_text='Enlace a la hoja de datos técnica del producto.', verbose_name='URL Hoja de datos'),
        ),
    ]
