# Generated by Django 6.0.7 on 2026-07-24 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0004_alter_modelodispositivo_url_datas_heet'),
        ('servicio', '0005_serviciocontratado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('numero_serie', models.CharField(max_length=150, unique=True, verbose_name='Número de serie')),
                ('codigo_interno', models.CharField(blank=True, help_text='Identificador interno utilizado por la empresa.', max_length=150, verbose_name='Código interno')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de instalación')),
                ('ubicacion', models.CharField(blank=True, help_text='Lugar físico donde está instalado el dispositivo.', max_length=150, verbose_name='Ubicación')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('MANTENIMIENTO', 'En mantenimiento'), ('RETIRADO', 'Retirado'), ('REEMPLAZADO', 'Reemplazado'), ('DANADO', 'Dañado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='dispositivo.modelodispositivo', verbose_name='Modelo')),
                ('servicio_contratado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='servicio.serviciocontratado', verbose_name='Servicio contratado')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ('modelo', 'numero_serie'),
            },
        ),
    ]
