# Generated by Django 6.0.7 on 2026-07-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0005_dispositivo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marca',
            name='unique_marca_nombre',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de retiro'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=150, verbose_name='Código interno'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='modelodispositivo',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipodispositivo',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
