# Generated by Django 6.0.7 on 2026-07-29 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0006_remove_marca_unique_marca_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado/rechazado por'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='estado_aprobacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', editable=False, help_text='Todo alta o modificación queda pendiente de aprobación hasta ser revisada.', max_length=20, verbose_name='Estado de aprobación'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de aprobación/rechazo'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='motivo_rechazo',
            field=models.TextField(blank=True, editable=False, verbose_name='Motivo de rechazo'),
        ),
    ]
