# Generated by Django 6.0.7 on 2026-07-30 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0006_remove_marca_unique_marca_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivo',
            options={'ordering': ('orden', 'nombre_comercial'), 'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ('orden', 'nombre'), 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='tipodispositivo',
            options={'ordering': ('orden', 'nombre'), 'verbose_name': 'Tipo de dispositivo', 'verbose_name_plural': 'Tipos de dispositivos'},
        ),
        migrations.RemoveConstraint(
            model_name='modelodispositivo',
            name='unique_modelo_por_marca',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='codigo_interno',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='fecha_instalacion',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='fecha_retiro',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='servicio_contratado',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo interno de adquisición.', max_digits=12, verbose_name='Costo'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción comercial del dispositivo.', max_length=500, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='nombre_comercial',
            field=models.CharField(default='null', help_text='Nombre utilizado internamente para el producto.', max_length=150, verbose_name='Nombre comercial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='orden',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Orden de visualización del catálogo.', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='precio_mercado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor de referencia del dispositivo.', max_digits=12, verbose_name='Precio de mercado'),
        ),
        migrations.AddField(
            model_name='marca',
            name='orden',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Orden utilizado para mostrar la marca.', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='modelodispositivo',
            name='codigo_fabricante',
            field=models.CharField(blank=True, help_text='Código asignado por el fabricante al modelo.', max_length=150, verbose_name='Código fabricante'),
        ),
        migrations.AddField(
            model_name='modelodispositivo',
            name='especificaciones',
            field=models.TextField(blank=True, help_text='Características técnicas del modelo.', verbose_name='Especificaciones técnicas'),
        ),
        migrations.AddField(
            model_name='modelodispositivo',
            name='orden',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Orden utilizado para mostrar el catálogo.', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='tipodispositivo',
            name='orden',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Orden utilizado para mostrar este registro.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='modelo',
            field=models.ForeignKey(help_text='Modelo técnico del dispositivo.', on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='dispositivo.modelodispositivo', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional de la marca.', max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(db_index=True, help_text='Nombre de la marca.', max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='sitio_web',
            field=models.URLField(blank=True, help_text='Sitio web de la marca.', verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='modelodispositivo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción general del modelo.', max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='modelodispositivo',
            name='marca',
            field=models.ForeignKey(help_text='Marca fabricante del dispositivo.', on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='dispositivo.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='modelodispositivo',
            name='nombre',
            field=models.CharField(db_index=True, help_text='Nombre o código comercial del modelo.', max_length=150, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='modelodispositivo',
            name='tipo_dispositivo',
            field=models.ForeignKey(help_text='Clasificación del dispositivo.', on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='dispositivo.tipodispositivo', verbose_name='Tipo de dispositivo'),
        ),
        migrations.AlterField(
            model_name='tipodispositivo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional del tipo de dispositivo.', max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipodispositivo',
            name='nombre',
            field=models.CharField(db_index=True, help_text='Nombre del tipo de dispositivo.', max_length=150, verbose_name='Nombre'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['modelo', 'nombre_comercial'], name='idx_dispositivo_modelo_nombre'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['orden', 'nombre_comercial'], name='idx_dispositivo_orden_nombre'),
        ),
        migrations.AddIndex(
            model_name='marca',
            index=models.Index(fields=['orden', 'nombre'], name='idx_marca_orden_nombre'),
        ),
        migrations.AddIndex(
            model_name='modelodispositivo',
            index=models.Index(fields=['marca', 'nombre'], name='idx_modelo_marca_nombre'),
        ),
        migrations.AddIndex(
            model_name='modelodispositivo',
            index=models.Index(fields=['tipo_dispositivo', 'nombre'], name='idx_modelo_tipo_nombre'),
        ),
        migrations.AddIndex(
            model_name='tipodispositivo',
            index=models.Index(fields=['orden', 'nombre'], name='idx_tipo_dispositivo_orden_nombre'),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.UniqueConstraint(fields=('modelo', 'nombre_comercial'), name='unique_dispositivo_modelo_nombre'),
        ),
        migrations.AddConstraint(
            model_name='marca',
            constraint=models.UniqueConstraint(fields=('nombre',), name='unique_marca_nombre'),
        ),
        migrations.AddConstraint(
            model_name='modelodispositivo',
            constraint=models.UniqueConstraint(fields=('marca', 'codigo_fabricante'), name='unique_modelo_marca_codigo_fabricante'),
        ),
        migrations.AddConstraint(
            model_name='tipodispositivo',
            constraint=models.UniqueConstraint(fields=('nombre',), name='unique_tipo_dispositivo_nombre'),
        ),
        migrations.RemoveField(
            model_name='modelodispositivo',
            name='ean',
        ),
        migrations.RemoveField(
            model_name='modelodispositivo',
            name='fabricado',
        ),
        migrations.RemoveField(
            model_name='modelodispositivo',
            name='fabricante_codigo',
        ),
        migrations.RemoveField(
            model_name='modelodispositivo',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='modelodispositivo',
            name='url_datas_heet',
        ),
    ]
