# Generated by Django 6.0.7 on 2026-07-30 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0007_alter_dispositivo_options_alter_marca_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tipodispositivo',
            new_name='idx_tipo_disp_ord_nom',
            old_name='idx_tipo_dispositivo_orden_nombre',
        ),
    ]
