# Generated by Django 6.0.7 on 2026-07-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0008_rename_idx_tipo_dispositivo_orden_nombre_idx_tipo_disp_ord_nom'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tipodispositivo',
            name='unique_tipo_dispositivo_nombre',
        ),
        migrations.AddConstraint(
            model_name='tipodispositivo',
            constraint=models.UniqueConstraint(fields=('nombre',), name='unique_tipo_disp_nombre'),
        ),
    ]
