# Generated by Django 6.0.7 on 2026-08-03 01:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta_cliente', '0003_alter_sucursal_cuenta_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(db_index=True, help_text='Nombre o referencia del presupuesto.', max_length=150, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('moneda', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=3, verbose_name='Moneda')),
                ('fecha_emision', models.DateField(db_index=True, help_text='Fecha en la que se emitió el presupuesto.', verbose_name='Fecha de emisión')),
                ('dias_validez', models.PositiveSmallIntegerField(default=15, help_text='Cantidad de días de validez del presupuesto.', verbose_name='Días de validez')),
                ('fecha_vencimiento', models.DateField(blank=True, db_index=True, help_text='Fecha hasta la cual el presupuesto mantiene su validez.', null=True, verbose_name='Fecha de vencimiento')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], db_index=True, default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Suma de los subtotales de los conceptos del presupuesto.', max_digits=12, verbose_name='Subtotal')),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Descuento total aplicado al presupuesto.', max_digits=12, verbose_name='Descuento total')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Importe total correspondiente a impuestos.', max_digits=12, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Importe final del presupuesto.', max_digits=12, verbose_name='Total')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='cuenta_cliente.sucursal', verbose_name='Sucursal')),
                ('vendedor', models.ForeignKey(help_text='Usuario responsable de la elaboración del presupuesto.', on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PresupuestoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(help_text='Descripción del concepto comercial.', verbose_name='Descripción')),
                ('orden', models.PositiveSmallIntegerField(default=1, help_text='Orden de presentación del concepto dentro del presupuesto.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('unidad', models.CharField(choices=[('UN', 'Unidad'), ('M', 'Metro'), ('M2', 'Metro cuadrado'), ('M3', 'Metro cúbico'), ('H', 'Hora'), ('D', 'Día'), ('MES', 'Mes'), ('SER', 'Servicio'), ('LIC', 'Licencia'), ('CAJ', 'Caja'), ('ROL', 'Rollo'), ('KIT', 'Kit'), ('LOT', 'Lote')], default='UN', help_text='Unidad de medida del concepto.', max_length=5, verbose_name='Unidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio unitario')),
                ('descuento_importe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento')),
                ('impuestos_importe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Impuestos')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='presupuesto.presupuesto', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Concepto del presupuesto',
                'verbose_name_plural': 'Conceptos del presupuesto',
                'ordering': ('presupuesto', 'orden', 'codigo'),
            },
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['sucursal', 'estado'], name='idx_pres_sucursal_estado'),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['fecha_emision'], name='idx_pres_emision'),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['fecha_vencimiento'], name='idx_pres_venc'),
        ),
        migrations.AddIndex(
            model_name='presupuestoitem',
            index=models.Index(fields=['presupuesto', 'orden'], name='idx_presitem_ord'),
        ),
        migrations.AddConstraint(
            model_name='presupuestoitem',
            constraint=models.UniqueConstraint(fields=('presupuesto', 'orden'), name='unique_presupuesto_orden'),
        ),
    ]
