# Generated by Django 6.0.7 on 2026-08-03 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0009_remove_tipodispositivo_unique_tipo_dispositivo_nombre_and_more'),
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestoitem',
            name='dispositivo',
            field=models.ForeignKey(blank=True, help_text='Producto del catálogo asociado al concepto.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_items', to='dispositivo.dispositivo', verbose_name='Dispositivo'),
        ),
    ]
