# Generated by Django 6.0.7 on 2026-08-03 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_presupuestoitem_dispositivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestoitem',
            name='dispositivo',
        ),
    ]
