# Generated by Django 6.0.7 on 2026-08-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_remove_presupuestoitem_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense')], default='ARS', max_length=3, verbose_name='Moneda'),
        ),
    ]
