# Generated by Django 6.0.7 on 2026-07-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio base')),
                ('requiere_dispositivos', models.BooleanField(default=True, verbose_name='Requiere dispositivos')),
                ('requiere_instalacion', models.BooleanField(default=True, verbose_name='Requiere instalación')),
                ('genera_abono', models.BooleanField(default=True, verbose_name='Genera abono')),
                ('permite_facturacion', models.BooleanField(default=True, verbose_name='Permite facturación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='servicio.categoriaservicio', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ('nombre',),
                'constraints': [models.UniqueConstraint(fields=('nombre',), name='unique_servicio_nombre')],
            },
        ),
    ]
