# Generated by Django 6.0.7 on 2026-07-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='precio_base',
            new_name='precio_abono',
        ),
    ]
