# Generated by Django 6.0.7 on 2026-07-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_rename_precio_base_servicio_precio_abono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio_abono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio abono'),
        ),
    ]
