# Generated by Django 6.0.7 on 2026-07-24 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0002_alter_cuentacliente_codigo_postal_and_more'),
        ('servicio', '0004_alter_servicio_precio_abono'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioContratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('nombre_comercial', models.CharField(blank=True, help_text='Nombre opcional para identificar este servicio en la sucursal.', max_length=150, verbose_name='Nombre comercial')),
                ('precio_abono', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio del abono')),
                ('fecha_alta', models.DateField(verbose_name='Fecha de alta')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de instalación')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('renovacion_automatica', models.BooleanField(default=True, verbose_name='Renovación automática')),
                ('facturar', models.BooleanField(default=True, verbose_name='Facturar')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('servicio', models.ForeignKey(help_text='Nombre interno para identificar el servicio.', on_delete=django.db.models.deletion.PROTECT, related_name='servicios_contratados', to='servicio.servicio', verbose_name='Servicio')),
                ('sucursal', models.ForeignKey(help_text='Nombre interno para identificar la sucursal.', on_delete=django.db.models.deletion.PROTECT, related_name='servicios_contratados', to='cuenta_cliente.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Servicio contratado',
                'verbose_name_plural': 'Servicios contratados',
                'ordering': ('-fecha_alta', 'nombre_comercial'),
                'constraints': [models.UniqueConstraint(fields=('sucursal', 'servicio'), name='unique_servicio_por_sucursal')],
            },
        ),
    ]
