# Generated by Django 6.0.7 on 2026-07-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_serviciocontratado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicio',
            name='unique_servicio_nombre',
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='unique_servicio_categoria_nombre'),
        ),
    ]
