# Generated by Django 6.0.7 on 2026-07-25 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_remove_servicio_unique_servicio_nombre_and_more'),
        ('sistema', '0002_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('principal', models.BooleanField(default=False, help_text='Indica si este es el sistema principal del servicio.', verbose_name='Sistema principal')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_sistemas', to='servicio.servicio', verbose_name='Servicio')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicio_sistemas', to='sistema.sistema', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Sistema del servicio',
                'verbose_name_plural': 'Sistemas del servicio',
                'ordering': ('servicio', '-principal', 'sistema'),
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='sistemas',
            field=models.ManyToManyField(blank=True, related_name='servicios', through='servicio.ServicioSistema', to='sistema.sistema', verbose_name='Sistemas'),
        ),
        migrations.AddConstraint(
            model_name='serviciosistema',
            constraint=models.UniqueConstraint(fields=('servicio', 'sistema'), name='unique_servicio_sistema'),
        ),
    ]
