# Generated by Django 6.0.7 on 2026-07-25 03:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0002_alter_cuentacliente_codigo_postal_and_more'),
        ('servicio', '0007_serviciosistema_servicio_sistemas_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='serviciocontratado',
            name='unique_servicio_por_sucursal',
        ),
        migrations.AddField(
            model_name='serviciocontratado',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento aplicado al abono.', max_digits=5, verbose_name='Descuento (%)'),
        ),
        migrations.AlterField(
            model_name='serviciocontratado',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='serviciocontratado',
            name='facturar',
            field=models.BooleanField(default=True, help_text='Indica si este servicio debe incluirse en la facturación.', verbose_name='Facturar'),
        ),
        migrations.AlterField(
            model_name='serviciocontratado',
            name='nombre_comercial',
            field=models.CharField(blank=True, help_text='Nombre opcional para identificar este servicio dentro de la sucursal.', max_length=150, verbose_name='Nombre comercial'),
        ),
        migrations.AlterField(
            model_name='serviciocontratado',
            name='servicio',
            field=models.ForeignKey(help_text='Servicio contratado por la sucursal.', on_delete=django.db.models.deletion.PROTECT, related_name='servicios_contratados', to='servicio.servicio', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='serviciocontratado',
            name='sucursal',
            field=models.ForeignKey(help_text='Sucursal donde se presta el servicio.', on_delete=django.db.models.deletion.PROTECT, related_name='servicios_contratados', to='cuenta_cliente.sucursal', verbose_name='Sucursal'),
        ),
    ]
