# Generated by Django 6.0.7 on 2026-07-26 19:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0003_alter_sucursal_cuenta_cliente'),
        ('servicio', '0008_remove_serviciocontratado_unique_servicio_por_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciocontratado',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento (%)'),
        ),
        migrations.AddConstraint(
            model_name='serviciocontratado',
            constraint=models.UniqueConstraint(fields=('sucursal', 'servicio'), name='unique_servicio_contratado_por_sucursal'),
        ),
    ]
