# Generated by Django 6.0.7 on 2026-07-28 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_alter_proyecto_descripcion'),
        ('servicio', '0009_alter_serviciocontratado_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocontratado',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto que dio origen a este servicio contratado, si corresponde. Puede no provenir de ningún proyecto.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_contratados', to='proyecto.proyecto', verbose_name='Proyecto de origen'),
        ),
    ]
