# Generated by Django 6.0.7 on 2026-07-24 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
                ('disponible', models.BooleanField(default=True, help_text='Indica si el sistema está disponible para nuevas instalaciones.', verbose_name='Disponible')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sistemas', to='sistema.categoriasistema', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
                'ordering': ('categoria__nombre', 'nombre'),
                'constraints': [models.UniqueConstraint(fields=('categoria', 'nombre'), name='unique_sistema_por_categoria')],
            },
        ),
    ]
