# Generated by Django 6.0.7 on 2026-07-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasistema',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada de la categoría tecnológica.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoriasistema',
            name='nombre',
            field=models.CharField(help_text='Nombre de la categoría tecnológica.', max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
