# Generated by Django 6.0.7 on 2026-07-28 23:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoTelecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de solicitud')),
                ('sitio_obra', models.CharField(max_length=255, verbose_name='Sitio de obra')),
                ('tipo_trabajo', models.CharField(choices=[('INSTALACION', 'Instalación'), ('DESINSTALACION', 'Desinstalación'), ('REINSTALACION', 'Reinstalación')], max_length=20, verbose_name='Tipo de trabajo')),
                ('distancia_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Distancia por ruta (ida y vuelta) entre la ciudad cabecera y el sitio de obra. Es informativa: si corresponde recargo por kilometraje, agregalo como línea de detalle del catálogo, igual que en la planilla original.', max_digits=8, verbose_name='Distancia (km)')),
                ('factor_multiplicador_zona', models.DecimalField(decimal_places=2, default=Decimal('1.00'), editable=False, max_digits=5, verbose_name='Factor de zona aplicado')),
                ('factor_recargo', models.DecimalField(decimal_places=2, default=Decimal('1.00'), editable=False, max_digits=5, verbose_name='Factor de recargo aplicado')),
                ('subtotal_mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Subtotal mano de obra (ARS)')),
                ('subtotal_materiales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Subtotal materiales (USD)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Presupuesto de telecom',
                'verbose_name_plural': 'Presupuestos de telecom',
                'ordering': ('-fecha_solicitud',),
            },
        ),
        migrations.CreateModel(
            name='RecargoTelecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('INSTALACION_NOCTURNO_0_50', 'Instalación nocturna (0 a 50 km)'), ('INSTALACION_NOCTURNO_50_MAS', 'Instalación nocturna (+50 km)'), ('DESINSTALACION_DIURNO_50_MAS', 'Desinstalación diurna (+50 km)'), ('DESINSTALACION_NOCTURNO_0_50', 'Desinstalación nocturna (0 a 50 km)'), ('REINSTALACION_NOCTURNO_0_50', 'Reinstalación nocturna (0 a 50 km)'), ('REINSTALACION_NOCTURNO_50_MAS', 'Reinstalación nocturna (+50 km)'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo'), ('FERIADO', 'Feriado')], max_length=40, unique=True, verbose_name='Tipo de recargo')),
                ('factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplica el subtotal de mano de obra (1.20 = recargo del 20%).', max_digits=5, verbose_name='Factor')),
            ],
            options={
                'verbose_name': 'Recargo de telecom',
                'verbose_name_plural': 'Recargos de telecom',
                'ordering': ('tipo',),
            },
        ),
        migrations.CreateModel(
            name='ZonaTelecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('region', models.CharField(blank=True, help_text='Agrupación informativa de la zona (por ejemplo: NOA, SUR, Litoral).', max_length=50, verbose_name='Región')),
                ('provincia', models.CharField(max_length=100, unique=True, verbose_name='Provincia')),
                ('ciudad_cabecera', models.CharField(help_text='Ciudad de referencia para calcular la distancia por ruta hasta el sitio de obra.', max_length=100, verbose_name='Ciudad cabecera')),
                ('factor_multiplicador', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplica el subtotal de mano de obra del presupuesto (1.00 = sin ajuste).', max_digits=5, verbose_name='Factor multiplicador')),
            ],
            options={
                'verbose_name': 'Zona de telecom',
                'verbose_name_plural': 'Zonas de telecom',
                'ordering': ('provincia',),
            },
        ),
        migrations.CreateModel(
            name='ConceptoTelecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('MANO_DE_OBRA', 'Mano de obra'), ('MATERIAL', 'Material')], max_length=20, verbose_name='Tipo')),
                ('nombre', models.CharField(help_text='Nombre corto del ítem, para listados y selección rápida.', max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Detalle completo de lo que incluye el ítem.', verbose_name='Descripción')),
                ('moneda', models.CharField(choices=[('PESOS', 'Pesos'), ('DOLAR', 'Dólares')], default='PESOS', max_length=10, verbose_name='Moneda')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio unitario')),
            ],
            options={
                'verbose_name': 'Concepto de telecom',
                'verbose_name_plural': 'Conceptos de telecom',
                'ordering': ('tipo', 'nombre'),
                'constraints': [models.UniqueConstraint(fields=('tipo', 'nombre'), name='unique_concepto_telecom_tipo_nombre')],
            },
        ),
        migrations.CreateModel(
            name='DetallePresupuestoTelecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_concepto', models.CharField(editable=False, max_length=150, verbose_name='Concepto')),
                ('tipo', models.CharField(choices=[('MANO_DE_OBRA', 'Mano de obra'), ('MATERIAL', 'Material')], editable=False, max_length=20, verbose_name='Tipo')),
                ('moneda', models.CharField(choices=[('PESOS', 'Pesos'), ('DOLAR', 'Dólares')], editable=False, max_length=10, verbose_name='Moneda')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Precio unitario')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Subtotal')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_presupuesto', to='telecom.conceptotelecom', verbose_name='Concepto')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='telecom.presupuestotelecom', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Detalle de presupuesto de telecom',
                'verbose_name_plural': 'Detalles de presupuesto de telecom',
                'ordering': ('presupuesto', 'id'),
            },
        ),
        migrations.AddField(
            model_name='presupuestotelecom',
            name='recargo',
            field=models.ForeignKey(blank=True, help_text='Recargo por turno/distancia/día, si corresponde. Puede no llevar ninguno.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='telecom.recargotelecom', verbose_name='Recargo aplicado'),
        ),
        migrations.AddField(
            model_name='presupuestotelecom',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='telecom.zonatelecom', verbose_name='Zona'),
        ),
    ]
