# Generated by Django 6.0.7 on 2026-07-30 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0003_alter_sucursal_cuenta_cliente'),
        ('telecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestotelecom',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='cuenta_cliente.sucursal', verbose_name='Sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presupuestotelecom',
            name='w0',
            field=models.CharField(blank=True, help_text='Codigo con el que se maneja telecom', max_length=150, verbose_name='WO'),
        ),
    ]
