# Generated by Django 6.0.7 on 2026-07-30 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0003_alter_sucursal_cuenta_cliente'),
        ('telecom', '0002_presupuestotelecom_sucursal_presupuestotelecom_w0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestotelecom',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='cuenta_cliente.sucursal', verbose_name='Sucursal'),
        ),
    ]
