# Generated by Django 6.0.7 on 2026-07-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0003_alter_presupuestotelecom_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestotelecom',
            name='w0',
        ),
        migrations.AddField(
            model_name='presupuestotelecom',
            name='codigo_wo',
            field=models.CharField(blank=True, help_text='Número de Work Order (orden de trabajo) con el que la empresa de telecom identifica este trabajo.', max_length=150, verbose_name='WO'),
        ),
    ]
