# Generated by Django 6.0.7 on 2026-08-03 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0003_alter_sucursal_cuenta_cliente'),
        ('telecom', '0004_remove_presupuestotelecom_w0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestotelecom',
            name='recargo',
            field=models.ForeignKey(blank=True, help_text='Recargo por turno/distancia/día, si corresponde. Puede no llevar ninguno.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_telecom', to='telecom.recargotelecom', verbose_name='Recargo aplicado'),
        ),
        migrations.AlterField(
            model_name='presupuestotelecom',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_telecom', to='cuenta_cliente.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='presupuestotelecom',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_telecom', to='telecom.zonatelecom', verbose_name='Zona'),
        ),
    ]
