# Generated by Django 6.0.7 on 2026-08-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0005_alter_presupuestotelecom_recargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptotelecom',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense')], default='ARS', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='detallepresupuestotelecom',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense')], editable=False, max_length=10, verbose_name='Moneda'),
        ),
    ]
