from .roles import *
from .querysets import *

from .permisos import (
    tiene_permiso,
    tiene_permisos,
    tiene_algun_permiso,
    puede_ver_clientes,
    puede_crear_clientes,
    puede_editar_clientes,
    puede_ver_sucursales,
    puede_ver_proyectos,
    puede_crear_proyectos,
    puede_editar_proyectos,
    puede_eliminar_proyectos,
    puede_ver_costos_proyecto,
    puede_ver_ordenes_trabajo,
    puede_crear_ordenes_trabajo,
    puede_editar_ordenes_trabajo,
    puede_cerrar_orden_trabajo,
    puede_asignar_tecnicos_ot,
    puede_agregar_seguimiento_ot,
    puede_subir_archivo_ot,
    puede_facturar_orden_trabajo,
    puede_registrar_cobro_ot,
    puede_ver_instalaciones,
    puede_crear_instalaciones,
    puede_editar_instalaciones,
    puede_finalizar_instalacion,
    puede_gestionar_dispositivos_instalados,
    puede_ver_credenciales_dispositivo,
    puede_ver_catalogo,
    puede_editar_catalogo,
    puede_ver_dispositivos,
    puede_editar_dispositivos,
    puede_ver_usuarios,
    puede_crear_usuarios,
    puede_editar_usuarios,
    puede_administrar_roles,
)
from .querysets import (
    filtrar_cuentas_cliente,
    filtrar_sucursales,
    filtrar_proyectos,
    filtrar_detalles_proyecto,
    filtrar_ordenes_trabajo,
    filtrar_tecnicos_orden_trabajo,
    filtrar_seguimientos_ot,
    filtrar_archivos_ot,
    filtrar_instalaciones,
    filtrar_dispositivos_instalados,
    filtrar_tecnicos_instalacion,
)


__all__ = (
    # Roles
    "ROL_SUPERADMIN",
    "ROL_GERENCIA",
    "ROL_AUDITORES",
    "ROL_TECNICOS",
    "ROL_USUARIOS_CLIENTE",
    "ROL_PROVEEDORES",
    "ROL_CREADORES_PROYECTO",
    "ROLES_INTERNOS",
    "ROLES_EXTERNOS",
    "ROLES_DISPONIBLES",
    "obtener_nombres_grupos",
    "pertenece_a_grupo",
    "pertenece_a_alguno",
    "pertenece_a_todos",
    "es_superadmin",
    "es_gerencia",
    "es_auditor",
    "es_tecnico",
    "es_usuario_cliente",
    "es_proveedor",
    "es_creador_proyecto",
    "es_usuario_interno",
    "es_usuario_externo",
    "tiene_acceso_global",

    # Permisos
    "tiene_permiso",
    "tiene_permisos",
    "tiene_algun_permiso",
    "puede_ver_clientes",
    "puede_crear_clientes",
    "puede_editar_clientes",
    "puede_ver_sucursales",
    "puede_ver_proyectos",
    "puede_crear_proyectos",
    "puede_editar_proyectos",
    "puede_eliminar_proyectos",
    "puede_ver_costos_proyecto",
    "puede_ver_ordenes_trabajo",
    "puede_crear_ordenes_trabajo",
    "puede_editar_ordenes_trabajo",
    "puede_cerrar_orden_trabajo",
    "puede_asignar_tecnicos_ot",
    "puede_agregar_seguimiento_ot",
    "puede_subir_archivo_ot",
    "puede_facturar_orden_trabajo",
    "puede_registrar_cobro_ot",
    "puede_ver_instalaciones",
    "puede_crear_instalaciones",
    "puede_editar_instalaciones",
    "puede_finalizar_instalacion",
    "puede_gestionar_dispositivos_instalados",
    "puede_ver_credenciales_dispositivo",
    "puede_ver_catalogo",
    "puede_editar_catalogo",
    "puede_ver_dispositivos",
    "puede_editar_dispositivos",
    "puede_ver_usuarios",
    "puede_crear_usuarios",
    "puede_editar_usuarios",
    "puede_administrar_roles",

    # QuerySets
    "filtrar_cuentas_cliente",
    "filtrar_sucursales",
    "filtrar_proyectos",
    "filtrar_detalles_proyecto",
    "filtrar_ordenes_trabajo",
    "filtrar_tecnicos_orden_trabajo",
    "filtrar_seguimientos_ot",
    "filtrar_archivos_ot",
    "filtrar_instalaciones",
    "filtrar_dispositivos_instalados",
    "filtrar_tecnicos_instalacion",
)