# Generated by Django 6.0.7 on 2026-08-05 12:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(db_index=True, help_text='Nombre identificativo de la categoría.', max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción general de los conceptos agrupados en esta categoría.', max_length=500, verbose_name='Descripción')),
                ('orden', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Orden de presentación de la categoría dentro del catálogo.', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría de catálogo',
                'verbose_name_plural': 'Categorías de catálogo',
                'ordering': ('orden', 'nombre'),
                'indexes': [models.Index(fields=['orden', 'nombre'], name='idx_catcat_orden_nombre')],
                'constraints': [models.UniqueConstraint(fields=('nombre',), name='unique_categoria_catalogo_nombre')],
            },
        ),
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('MATERIAL', 'Material'), ('INSUMO', 'Insumo'), ('MANO_OBRA', 'Mano de obra'), ('SERVICIO', 'Servicio'), ('LICENCIA', 'Licencia'), ('VIATICO', 'Viático'), ('OTRO', 'Otro')], db_index=True, help_text='Tipo comercial u operativo del concepto.', max_length=20, verbose_name='Tipo')),
                ('nombre', models.CharField(help_text='Nombre comercial o identificativo del ítem.', max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción comercial, técnica u operativa del ítem.', max_length=500, verbose_name='Descripción')),
                ('unidad', models.CharField(choices=[('UN', 'Unidad'), ('M', 'Metro'), ('M2', 'Metro cuadrado'), ('M3', 'Metro cúbico'), ('H', 'Hora'), ('D', 'Día'), ('MES', 'Mes'), ('SER', 'Servicio'), ('LIC', 'Licencia'), ('CAJ', 'Caja'), ('ROL', 'Rollo'), ('KIT', 'Kit'), ('LOT', 'Lote')], default='UN', help_text='Unidad utilizada para calcular la cantidad del concepto.', max_length=10, verbose_name='Unidad de medida')),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo interno o valor de adquisición del concepto.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio sugerido para utilizar en proyectos y documentos comerciales.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de venta')),
                ('controla_stock', models.BooleanField(default=False, help_text='Indica si el ítem deberá participar del control de existencias.', verbose_name='Controla stock')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de presentación del ítem dentro de su categoría.', verbose_name='Orden')),
                ('categoria', models.ForeignKey(help_text='Categoría utilizada para organizar el ítem.', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalogo.categoriacatalogo', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Ítem de catálogo',
                'verbose_name_plural': 'Ítems de catálogo',
                'ordering': ('categoria', 'orden', 'nombre'),
                'indexes': [models.Index(fields=['categoria', 'tipo'], name='idx_itemcat_cat_tipo'), models.Index(fields=['tipo', 'controla_stock'], name='idx_itemcat_tipo_stock'), models.Index(fields=['categoria', 'orden', 'nombre'], name='idx_itemcat_cat_orden')],
                'constraints': [models.UniqueConstraint(fields=('categoria', 'nombre'), name='unique_item_categoria_nombre')],
            },
        ),
    ]
