# Generated by Django 6.0.7 on 2026-07-24 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('tipo_cliente', models.CharField(choices=[('PERSONA', 'Persona Física'), ('EMPRESA', 'Empresa')], default='PERSONA', max_length=20, verbose_name='Tipo de cliente')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido')),
                ('dni', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI')),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón social')),
                ('cuit', models.CharField(blank=True, max_length=20, null=True, verbose_name='CUIT')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('piso', models.CharField(blank=True, max_length=10, null=True, verbose_name='Piso')),
                ('departamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Departamento')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código postal')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Cuenta Cliente',
                'verbose_name_plural': 'Cuentas Clientes',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de sucursal')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('piso', models.CharField(blank=True, max_length=10, null=True, verbose_name='Piso')),
                ('departamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Departamento')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código postal')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cuenta_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='cuenta_cliente.cuentacliente', verbose_name='Cuenta cliente')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['codigo'],
                'constraints': [models.UniqueConstraint(fields=('cuenta_cliente', 'nombre'), name='unique_sucursal_por_cliente')],
            },
        ),
    ]
