# Generated by Django 6.0.7 on 2026-07-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacliente',
            name='codigo_postal',
            field=models.CharField(max_length=20, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='codigo_postal',
            field=models.CharField(max_length=20, verbose_name='Código postal'),
        ),
    ]
