# Generated by Django 6.0.7 on 2026-07-26 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0002_alter_cuentacliente_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='cuenta_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='cuenta_cliente.cuentacliente', verbose_name='Cuenta cliente'),
        ),
    ]
