# Generated by Django 6.0.7 on 2026-07-24 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta_cliente', '0002_alter_cuentacliente_codigo_postal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('PRESUPUESTADO', 'Presupuestado'), ('APROBADO', 'Aprobado'), ('EN_EJECUCION', 'En ejecución'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PLANIFICADO', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_finalizacion', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='cuenta_cliente.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ('-created_at',),
            },
        ),
    ]
