# Generated by Django 6.0.7 on 2026-07-24 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0005_dispositivo'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('descripcion', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('modelo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_proyecto', to='dispositivo.modelodispositivo', verbose_name='Modelo de dispositivo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proyecto.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Detalle de proyecto',
                'verbose_name_plural': 'Detalles de proyecto',
                'ordering': ('proyecto', 'modelo_dispositivo'),
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'modelo_dispositivo'), name='unique_modelo_por_proyecto')],
            },
        ),
    ]
