# Generated by Django 6.0.7 on 2026-07-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_detalleproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
