# Generated by Django 6.0.7 on 2026-08-02 20:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0003_alter_sucursal_cuenta_cliente'),
        ('dispositivo', '0009_remove_tipodispositivo_unique_tipo_dispositivo_nombre_and_more'),
        ('proyecto', '0003_alter_proyecto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad prevista para este proyecto.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('descripcion', models.CharField(blank=True, default='', help_text='Descripción adicional del requerimiento.', max_length=500, verbose_name='Descripción')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Requerimiento del proyecto',
                'verbose_name_plural': 'Requerimientos del proyecto',
                'ordering': ('proyecto', 'dispositivo'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='detalleproyecto',
            name='unique_modelo_por_proyecto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_planificada_finalizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha planificada de finalización'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_planificada_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha planificada de inicio'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='titulo',
            field=models.CharField(default=1, max_length=150, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('PRESUPUESTADO', 'Presupuestado'), ('APROBADO', 'Aprobado'), ('EN_EJECUCION', 'En ejecución'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PLANIFICADO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, help_text='Fecha real en la que finalizó el proyecto.', null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha real en la que comenzó la ejecución del proyecto.', null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='observaciones',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['estado'], name='idx_proy_estado'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['fecha_planificada_inicio'], name='idx_proy_fec_ini'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['fecha_planificada_finalizacion'], name='idx_proy_fec_fin'),
        ),
        migrations.AddField(
            model_name='proyectorequerimiento',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_proyecto', to='dispositivo.modelodispositivo', verbose_name='Dispositivo'),
        ),
        migrations.AddField(
            model_name='proyectorequerimiento',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='proyecto.proyecto', verbose_name='Proyecto'),
        ),
        migrations.RemoveField(
            model_name='detalleproyecto',
            name='modelo_dispositivo',
        ),
        migrations.RemoveField(
            model_name='detalleproyecto',
            name='proyecto',
        ),
        migrations.AddIndex(
            model_name='proyectorequerimiento',
            index=models.Index(fields=['proyecto'], name='idx_req_proyecto'),
        ),
        migrations.AddConstraint(
            model_name='proyectorequerimiento',
            constraint=models.UniqueConstraint(fields=('proyecto', 'dispositivo'), name='unique_req_proyecto'),
        ),
        migrations.DeleteModel(
            name='DetalleProyecto',
        ),
    ]
