# Generated by Django 6.0.7 on 2026-08-04 00:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0003_alter_sucursal_cuenta_cliente'),
        ('dispositivo', '0009_remove_tipodispositivo_unique_tipo_dispositivo_nombre_and_more'),
        ('proyecto', '0004_proyectorequerimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('DISPOSITIVO', 'Dispositivo'), ('SERVICIO', 'Servicio'), ('MATERIAL', 'Material'), ('MANO_OBRA', 'Mano de obra'), ('LICENCIA', 'Licencia'), ('VIATICO', 'Viático'), ('OTRO', 'Otro')], db_index=True, default='DISPOSITIVO', max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción comercial o técnica del concepto.', verbose_name='Descripción')),
                ('orden', models.PositiveSmallIntegerField(default=1, help_text='Orden de presentación del detalle dentro del proyecto.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('unidad', models.CharField(choices=[('UN', 'Unidad'), ('M', 'Metro'), ('M2', 'Metro cuadrado'), ('M3', 'Metro cúbico'), ('H', 'Hora'), ('D', 'Día'), ('MES', 'Mes'), ('SER', 'Servicio'), ('LIC', 'Licencia'), ('CAJ', 'Caja'), ('ROL', 'Rollo'), ('KIT', 'Kit'), ('LOT', 'Lote')], default='UN', max_length=5, verbose_name='Unidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio unitario')),
                ('descuento_importe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento')),
                ('impuestos_importe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Impuestos')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Detalle del proyecto',
                'verbose_name_plural': 'Detalles del proyecto',
                'ordering': ('proyecto', 'orden', 'codigo'),
            },
        ),
        migrations.RemoveIndex(
            model_name='proyectorequerimiento',
            name='idx_req_proyecto',
        ),
        migrations.RemoveConstraint(
            model_name='proyectorequerimiento',
            name='unique_req_proyecto',
        ),
        migrations.RemoveIndex(
            model_name='proyecto',
            name='idx_proy_fec_ini',
        ),
        migrations.RemoveIndex(
            model_name='proyecto',
            name='idx_proy_fec_fin',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Suma de los descuentos aplicados a los detalles.', max_digits=12, verbose_name='Descuento total'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateField(db_index=True, default=datetime.date(2026, 8, 3), help_text='Fecha comercial u operativa de creación del proyecto.', verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_planificada',
            field=models.DateField(blank=True, db_index=True, help_text='Fecha prevista para comenzar la ejecución del proyecto.', null=True, verbose_name='Fecha planificada'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Suma de los impuestos aplicados a los detalles.', max_digits=12, verbose_name='Impuestos'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense')], default='ARS', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(db_index=True, default='Proyecto migrado', help_text='Nombre o referencia principal del proyecto.', max_length=150, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='responsable',
            field=models.ForeignKey(default=1, help_text='Usuario responsable de administrar el proyecto.', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Suma de los subtotales de los detalles del proyecto.', max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Importe final del proyecto.', max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción general del alcance del proyecto.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION', 'Pendiente de aprobación'), ('APROBADO', 'Aprobado'), ('PLANIFICADO', 'Planificado'), ('EN_EJECUCION', 'En ejecución'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], db_index=True, default='BORRADOR', help_text='Estado actual del ciclo de vida del proyecto.', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, help_text='Fecha real en que finalizó el proyecto.', null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha real en que comenzó la ejecución del proyecto.', null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='sucursal',
            field=models.ForeignKey(help_text='Sucursal para la cual se realiza el proyecto.', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='cuenta_cliente.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['fecha_creacion'], name='idx_proy_fec_crea'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['fecha_planificada'], name='idx_proy_fec_plan'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['sucursal', 'estado'], name='idx_proy_suc_estado'),
        ),
        migrations.AddField(
            model_name='proyectodetalle',
            name='dispositivo',
            field=models.ForeignKey(blank=True, help_text='Producto del catálogo asociado al detalle, si corresponde.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_detalles', to='dispositivo.dispositivo', verbose_name='Dispositivo'),
        ),
        migrations.AddField(
            model_name='proyectodetalle',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proyecto.proyecto', verbose_name='Proyecto'),
        ),
        migrations.RemoveField(
            model_name='proyectorequerimiento',
            name='dispositivo',
        ),
        migrations.RemoveField(
            model_name='proyectorequerimiento',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_planificada_finalizacion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_planificada_inicio',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='titulo',
        ),
        migrations.AddIndex(
            model_name='proyectodetalle',
            index=models.Index(fields=['proyecto', 'orden'], name='idx_proydet_proy_ord'),
        ),
        migrations.AddIndex(
            model_name='proyectodetalle',
            index=models.Index(fields=['tipo'], name='idx_proydet_tipo'),
        ),
        migrations.AddIndex(
            model_name='proyectodetalle',
            index=models.Index(fields=['dispositivo'], name='idx_proydet_dispositivo'),
        ),
        migrations.AddConstraint(
            model_name='proyectodetalle',
            constraint=models.UniqueConstraint(fields=('proyecto', 'orden'), name='uq_proydet_proy_orden'),
        ),
        migrations.DeleteModel(
            name='ProyectoRequerimiento',
        ),
    ]
