# Generated by Django 6.0.7 on 2026-08-05 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('dispositivo', '0009_remove_tipodispositivo_unique_tipo_dispositivo_nombre_and_more'),
        ('proyecto', '0005_proyectodetalle_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proyectodetalle',
            name='uq_proydet_proy_orden',
        ),
        migrations.RemoveIndex(
            model_name='proyectodetalle',
            name='idx_proydet_dispositivo',
        ),
        migrations.AddField(
            model_name='proyectodetalle',
            name='item_catalogo',
            field=models.ForeignKey(blank=True, help_text='Material, insumo, mano de obra, servicio, licencia o viático asociado al detalle.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_detalles', to='catalogo.itemcatalogo', verbose_name='Ítem de catálogo'),
        ),
        migrations.AlterField(
            model_name='proyectodetalle',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción utilizada dentro del proyecto.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proyectodetalle',
            name='dispositivo',
            field=models.ForeignKey(blank=True, help_text='Dispositivo técnico asociado al detalle, si corresponde.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_detalles', to='dispositivo.dispositivo', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='proyectodetalle',
            name='tipo',
            field=models.CharField(choices=[('DISPOSITIVO', 'Dispositivo'), ('MATERIAL', 'Material'), ('INSUMO', 'Insumo'), ('MANO_OBRA', 'Mano de obra'), ('SERVICIO', 'Servicio'), ('LICENCIA', 'Licencia'), ('VIATICO', 'Viático'), ('OTRO', 'Otro')], db_index=True, help_text='Clasificación comercial o técnica del detalle.', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='proyectodetalle',
            name='unidad',
            field=models.CharField(choices=[('UN', 'Unidad'), ('M', 'Metro'), ('M2', 'Metro cuadrado'), ('M3', 'Metro cúbico'), ('H', 'Hora'), ('D', 'Día'), ('MES', 'Mes'), ('SER', 'Servicio'), ('LIC', 'Licencia'), ('CAJ', 'Caja'), ('ROL', 'Rollo'), ('KIT', 'Kit'), ('LOT', 'Lote')], default='UN', max_length=10, verbose_name='Unidad'),
        ),
        migrations.AddConstraint(
            model_name='proyectodetalle',
            constraint=models.UniqueConstraint(fields=('proyecto', 'orden'), name='unique_proyecto_detalle_orden'),
        ),
    ]
