# Generated by Django 6.0.7 on 2026-08-15 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0003_alter_sucursal_cuenta_cliente'),
        ('proyecto', '0006_remove_proyectodetalle_uq_proydet_proy_orden_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_envio_cliente',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora en que el proyecto fue enviado al cliente.', null=True, verbose_name='Fecha de envío al cliente'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_recepcion_solicitud',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora en que se recibió la solicitud del cliente.', null=True, verbose_name='Fecha de recepción de la solicitud'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_respuesta_cliente',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora en que el cliente respondió respecto del proyecto.', null=True, verbose_name='Fecha de respuesta del cliente'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], db_index=True, default='normal', help_text='Prioridad comercial u operativa del proyecto.', max_length=20, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='respuesta_cliente',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', help_text='Indica si el cliente todavía no respondió, aceptó o rechazó el proyecto.', max_length=20, verbose_name='Respuesta del cliente'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario_envio_cliente',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró el envío del proyecto al cliente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_enviados_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario_recepcion_solicitud',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró la recepción de la solicitud del cliente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_recepcionados', to=settings.AUTH_USER_MODEL, verbose_name='Recepcionado por'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario_respuesta_cliente',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró la respuesta del cliente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_respuestas_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Respuesta registrada por'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['prioridad'], name='idx_proy_prioridad'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['respuesta_cliente'], name='idx_proy_resp_cli'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['fecha_recepcion_solicitud'], name='idx_proy_fec_recep'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['fecha_envio_cliente'], name='idx_proy_fec_envio'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['fecha_respuesta_cliente'], name='idx_proy_fec_resp'),
        ),
    ]
