# Generated by Django 6.0.7 on 2026-08-21 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_proyecto_fecha_envio_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_documento', models.DateTimeField(blank=True, help_text='Fecha y hora asociada al documento, fotografía o evidencia.', null=True, verbose_name='Fecha del documento')),
                ('archivo', models.FileField(help_text='Documento, fotografía, plano, informe o archivo relacionado con el proyecto.', upload_to='proyectos/%Y/%m/', verbose_name='Archivo')),
                ('descripcion', models.CharField(blank=True, default='', help_text='Descripción breve del contenido del archivo.', max_length=150, verbose_name='Descripción')),
                ('fecha_retiro', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora en que el archivo fue retirado del flujo documental.', null=True, verbose_name='Fecha de retiro')),
                ('motivo_retiro', models.CharField(blank=True, default='', editable=False, help_text='Motivo por el cual el archivo dejó de considerarse activo.', max_length=250, verbose_name='Motivo del retiro')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='proyecto.proyecto', verbose_name='Proyecto')),
                ('usuario', models.ForeignKey(editable=False, help_text='Usuario que registró formalmente el archivo en el proyecto.', on_delete=django.db.models.deletion.PROTECT, related_name='archivos_proyectos', to=settings.AUTH_USER_MODEL, verbose_name='Cargado por')),
                ('usuario_retiro', models.ForeignKey(blank=True, editable=False, help_text='Usuario que retiró formalmente el archivo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archivos_proyecto_retirados', to=settings.AUTH_USER_MODEL, verbose_name='Retirado por')),
            ],
            options={
                'verbose_name': 'Archivo de proyecto',
                'verbose_name_plural': 'Archivos de proyectos',
                'ordering': ('-is_active', '-fecha_documento', '-created_at'),
                'indexes': [models.Index(fields=['proyecto', 'is_active'], name='idx_proy_arch_act'), models.Index(fields=['proyecto', 'fecha_documento'], name='idx_proy_arch_fec')],
            },
        ),
    ]
