# Generated by Django 6.0.7 on 2026-08-24 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_proyectoarchivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoarchivo',
            name='drive_file_id',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Identificador único asignado por Google Drive.', max_length=255, verbose_name='ID de Google Drive'),
        ),
        migrations.AddField(
            model_name='proyectoarchivo',
            name='drive_mime_type',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, verbose_name='Tipo MIME de Google Drive'),
        ),
        migrations.AddField(
            model_name='proyectoarchivo',
            name='drive_nombre',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, verbose_name='Nombre en Google Drive'),
        ),
        migrations.AddField(
            model_name='proyectoarchivo',
            name='drive_web_view_link',
            field=models.URLField(blank=True, default='', editable=False, help_text='Enlace para abrir el documento en Google Drive.', max_length=1000, verbose_name='Enlace de Google Drive'),
        ),
        migrations.AddField(
            model_name='proyectoarchivo',
            name='origen',
            field=models.CharField(choices=[('LOCAL', 'Archivo local'), ('GOOGLE_DRIVE', 'Google Drive')], db_index=True, default='LOCAL', help_text='Indica dónde se encuentra almacenado el documento.', max_length=20, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='proyectoarchivo',
            name='archivo',
            field=models.FileField(blank=True, default='', help_text='Documento almacenado localmente por la aplicación.', upload_to='proyectos/%Y/%m/', verbose_name='Archivo local'),
        ),
        migrations.AlterField(
            model_name='proyectoarchivo',
            name='fecha_retiro',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de retiro'),
        ),
        migrations.AlterField(
            model_name='proyectoarchivo',
            name='motivo_retiro',
            field=models.CharField(blank=True, default='', editable=False, max_length=250, verbose_name='Motivo del retiro'),
        ),
        migrations.AlterField(
            model_name='proyectoarchivo',
            name='usuario_retiro',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archivos_proyecto_retirados', to=settings.AUTH_USER_MODEL, verbose_name='Retirado por'),
        ),
        migrations.AddIndex(
            model_name='proyectoarchivo',
            index=models.Index(fields=['proyecto', 'origen'], name='idx_proy_arch_ori'),
        ),
    ]
