# Generated by Django 6.0.7 on 2026-08-06 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_cliente', '0003_alter_sucursal_cuenta_cliente'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ('first_name', 'last_name', 'email'), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, default='', help_text='Cargo laboral o función descriptiva del usuario. No reemplaza los grupos ni permisos.', max_length=150, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cuenta_cliente',
            field=models.ForeignKey(blank=True, help_text='Cuenta a la que puede acceder el usuario cliente. Debe quedar vacía para usuarios internos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='cuenta_cliente.cuentacliente', verbose_name='Cuenta cliente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='observaciones',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal específica a la que se limita el acceso. Si queda vacía, el usuario podrá acceder al alcance autorizado de toda la cuenta cliente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='cuenta_cliente.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono'),
        ),
    ]
