# Generated by Django 6.0.7 on 2026-07-27 03:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta_cliente', '0003_alter_sucursal_cuenta_cliente'),
        ('servicio', '0009_alter_serviciocontratado_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeradorFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_venta', models.PositiveSmallIntegerField(help_text='Número identificador del punto de venta.', unique=True, verbose_name='Punto de venta')),
                ('ultimo_numero', models.PositiveIntegerField(default=0, help_text='Último número de factura generado.', verbose_name='Último número utilizado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Numerador de factura',
                'verbose_name_plural': 'Numeradores de factura',
                'ordering': ('punto_venta',),
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('punto_venta', models.PositiveSmallIntegerField(default=1, verbose_name='Punto de venta')),
                ('numero', models.PositiveIntegerField(editable=False, verbose_name='Número')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('fecha_anulacion', models.DateField(blank=True, null=True, verbose_name='Fecha de anulación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cuenta_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='cuenta_cliente.cuentacliente', verbose_name='Cuenta cliente')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='cuenta_cliente.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ('-fecha_emision', '-numero'),
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(help_text='Descripción del concepto facturado.', max_length=200, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('servicio_contratado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_facturacion', to='servicio.serviciocontratado', verbose_name='Servicio contratado')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de factura',
                'verbose_name_plural': 'Detalles de factura',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de pago')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe')),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta de crédito'), ('tarjeta_debito', 'Tarjeta de débito'), ('transferencia_bancaria', 'Transferencia bancaria'), ('mitad_mitad', 'Mitad (50%) al inicio y resto (50%) al finalizar'), ('cheque', 'Cheque'), ('otro', 'Otro')], max_length=30, verbose_name='Medio de pago')),
                ('numero_comprobante', models.CharField(blank=True, help_text='Referencia externa del pago (transferencia, operación, cheque, etc.).', max_length=100, verbose_name='Número de comprobante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='facturacion.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ('-fecha',),
            },
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.UniqueConstraint(fields=('punto_venta', 'numero'), name='unique_numero_factura_por_punto'),
        ),
    ]
