# Generated by Django 6.0.7 on 2026-07-28 02:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        ('servicio', '0009_alter_serviciocontratado_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ('-created_at',), 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='codigo_servicio',
            field=models.CharField(default='PENDIENTE', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='concepto',
            field=models.CharField(default='PENDIENTE', max_length=150, verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='factura',
            name='motivo_anulacion',
            field=models.TextField(blank=True, verbose_name='Motivo de anulación'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='servicio_contratado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_factura', to='servicio.serviciocontratado', verbose_name='Servicio contratado'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de anulación'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(db_index=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total'),
        ),
    ]
