# Generated by Django 6.0.7 on 2026-07-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_factura_options_remove_detallefactura_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='concepto',
            field=models.CharField(default='Sin concepto', max_length=150, verbose_name='Concepto'),
        ),
    ]
